kind: Service
apiVersion: v1
metadata:
  name: quickstart-kibana-ex
  namespace: default
  labels:
    common.k8s.elastic.co/type: kibana
    kibana.k8s.elastic.co/name: quickstart
spec:
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
  selector:
    common.k8s.elastic.co/type: kibana
    kibana.k8s.elastic.co/name: quickstart
  type: LoadBalancer
  sessionAffinity: None
